# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87a7993bc389969dd1b56e3e2bbefcf88ab9ec3b6effa4f6709dc775a835ffec624425c78036b9d339096c3856b21cf9efe9f84fd74664ccfd3a0af4fb1cd93f

test:
  secret_key_base: 23bf39af65d6eac7a4e9d4865b044c99b06a87cd41714bf33cb91fbb898ae371f929f98a9213304599069b9815bde040a057f3c91eb84e2139c932c5583fb497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
